name: CI/CD - Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HOST_DEPLOY: 54.198.164.202

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials.
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_AC }}
        aws-secret-access-key: ${{ secrets.AWS_SK }}
        aws-region: us-east-1
        role-duration-seconds: 1200
    
    - name: Build and push docker image
      run: |
        commit_hash=$(echo $(git show -s --format="%H" HEAD) | cut -c1-10)
        docker build -t jaraujof/flask-app:latest -t jaraujof/flask-app:$commit_hash .
        echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
        docker push jaraujof/flask-app:$commit_hash
        docker push jaraujof/flask-app:latest
      env: 
        DOCKERHUB_USER: ${{ secrets.DH_USER }}
        DOCKERHUB_PASS: ${{ secrets.DH_PASS }}
    # - name: Redeploy container
    #   run: |
    #     echo @$HOST_DEPLOY
    #     echo $commit_hash

    #     ssh -i uni-flask-app.pem ubuntu@$HOST_DEPLOY sudo docker stop uni-flask-app
    #     ssh -i uni-flask-app.pem ubuntu@$HOST_DEPLOY sudo docker rm uni-flask-app
    #     ssh -i uni-flask-app.pem ubuntu@$HOST_DEPLOY sudo docker run -d --name uni-flask-app -p 5000:5000 jaraujof/flask-app:latest
        
